---
- name: apt | configure for HTTPS transport
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
    state: present
  tags: apt

- name: common utilites are installed
  apt:
    name:
      - htop
      - vim
      - dnsutils
      - curl
    state: present
  tags: apt
