---
- name: Docker Install | Add Docker's apt key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Docker Install | Add Docker's apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    update_cache: true
    filename: docker.list

- name: Docker Install | Install Docker CE and Docker Compose
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
    state: present

- name: Install pip3
  package:
    name: python3-pip
    state: present

- name: Docker SDK | Add Docker SDK to Python
  pip:
    name: docker

- name: Create Docker network "services"
  docker_network:
    name: services
    driver: macvlan
    attachable: true
    ipam_config:
      - gateway: 10.65.3.1
        subnet: 10.65.3.0/24
    driver_options:
      parent: "{{ docker_net_interface }}.3"
